version: '3.7'

networks:
  zPluginNet:
    name: zPluginNet
    driver: bridge

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: elasticsearch
    networks:
      - zPluginNet
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.1
    container_name: kibana
    networks:
      - zPluginNet
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:8.16.1
    container_name: heartbeat
    networks:
      - zPluginNet
    volumes:
      - ./heartbeat.yaml:/usr/share/heartbeat/heartbeat.yml
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    command: ["heartbeat", "-e", "-strict.perms=false"]

volumes:
  es_data:
    driver: local

