version: '3.8'

networks:
  zPluginNet:
    name: zPluginNet
    driver: bridge

services:
  kibana:
    image: kibana:8.16.1
    container_name: kibana
    restart: always
    networks:
      - zPluginNet
    ports:
      - "5601:5601"
