version: '3.3'

networks:
  zPluginNet:
    name: zPluginNet
    driver: bridge

services:
  elasticsearch:
    image: elasticsearch:8.16.1
    container_name: elasticsearch
    networks:
      - zPluginNet
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Para desabilitar autenticação (apenas para testes)
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
  kibana:
    image: kibana:8.16.1
    container_name: kibana
    networks:
      - zPluginNet
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  es_data:
    driver: local
